<?php

namespace Database\Seeders;

use App\Models\FoodItem;
use Illuminate\Database\Seeder;

class FoodItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->info('Seeding food items...');
        
        // Truncate the table to start fresh
        // Uncomment this if you want to clear the table before seeding
        // FoodItem::truncate();
        
        $foodItems = [
            [
                'food_id' => '9e45e6d5-b597-4cfd-8843-a1149fcd7b2c',
                'name' => 'sri lankan hopper',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => '1',
                'weight_per_serving' => null,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-22 18:53:46',
                'updated_at' => '2025-02-25 18:11:03',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e473b47-337f-4bd9-8f3a-0df9fd9730e0',
                'name' => 'Scrambled egg / scrambled බිත්තර',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'Egg',
                'weight_per_serving' => 60,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-23 10:45:43',
                'updated_at' => '2025-03-09 10:38:26',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e4778ac-8455-453d-84f1-4a6bea690e05',
                'name' => 'Coconut water / පොල් , කුරුම්බා , තැබිලි වතුර',
                'description' => 'Water contents in coconut / පොල් කුරුම්බා තැබිලි වල ඇති වතුර',
                'serving_size' => 1,
                'serving_unit' => 'Cup ( 250 ml )',
                'weight_per_serving' => null,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-23 13:37:24',
                'updated_at' => '2025-02-23 13:37:24',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e477d53-e4d0-409d-8ec2-6780ad3ab965',
                'name' => 'Coconut meat / පොල් , කුරුම්බා , තැබිලි මදය',
                'description' => 'Contents inside count / පොල් , කුරුම්බා , තැබිලි වල ඇති මදය',
                'serving_size' => 1,
                'serving_unit' => 'Cup',
                'weight_per_serving' => null,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-23 13:50:25',
                'updated_at' => '2025-02-23 13:50:25',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e4935dd-7973-4b51-980f-b2aed5e7971b',
                'name' => 'Fish bun / මාලු පාන්',
                'description' => 'Sri Lankan style fish bun',
                'serving_size' => 1,
                'serving_unit' => 'Bun',
                'weight_per_serving' => 100,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-24 10:22:15',
                'updated_at' => '2025-03-10 09:52:14',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e4998ed-49f9-4b7f-abf0-ffd8d40b755f',
                'name' => 'Cooked White rice / පිසින ලද සම්බා බත්',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'plate',
                'weight_per_serving' => 150,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-24 14:59:14',
                'updated_at' => '2025-03-09 17:59:58',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e4b3597-174e-452c-b467-890c520e2a80',
                'name' => 'Sri Lankan tea with milk and sugar /තේ  සීනි පිටි සහිත',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'Cup',
                'weight_per_serving' => null,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-02-25 10:13:08',
                'updated_at' => '2025-02-25 10:13:08',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e5759ba-9f42-4d37-9676-eacd397eb849',
                'name' => 'Cheese ham pastry / චීස් හැම් පේස්ට්‍රී',
                'description' => 'Pastry found in Sri Lankan restaurant with cheese and ham',
                'serving_size' => 1,
                'serving_unit' => 'Piece',
                'weight_per_serving' => 100,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-03 11:04:07',
                'updated_at' => '2025-03-04 09:42:43',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e595978-c273-46de-aecd-192add0b6ab9',
                'name' => 'Vegetable patty / වෙජිටබල් පැටිස්',
                'description' => 'Sri Lankan type party made with vegetables',
                'serving_size' => 1,
                'serving_unit' => 'Patty',
                'weight_per_serving' => 50,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-04 10:55:03',
                'updated_at' => '2025-03-04 10:55:03',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e5b3b8c-bd20-467b-bd7d-0e8e67c9cb1a',
                'name' => 'Bread',
                'description' => 'Sri Lankan white bread / පාන්',
                'serving_size' => 1,
                'serving_unit' => 'Slice',
                'weight_per_serving' => 25,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-05 09:23:02',
                'updated_at' => '2025-03-05 09:23:02',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e634bbc-7ec3-47a9-b2ce-bc419b619659',
                'name' => 'Sri Lankan milk tea / කිරි සීනි මිශ්‍ර තේ',
                'description' => 'Made cup of tea with sugar , tea and milk',
                'serving_size' => 1,
                'serving_unit' => 'cup',
                'weight_per_serving' => 150,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 09:34:55',
                'updated_at' => '2025-03-09 09:34:55',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e635f58-3ecf-4ead-912e-f11804e3c672',
                'name' => 'Bacon / බේකන්',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'Slice',
                'weight_per_serving' => 8,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 10:29:45',
                'updated_at' => '2025-03-09 10:29:45',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e63fc2f-ff46-4d75-ac37-af13d299ad41',
                'name' => 'beer [lion strong ] / බියර් [ලයන් ස්ට්‍රොන්ග්]',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'caan',
                'weight_per_serving' => 500,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 17:48:19',
                'updated_at' => '2025-03-09 17:48:19',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e63fe1f-08c8-43bc-97f7-4be5a533089f',
                'name' => 'peanuts / රට කජු',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'peanut',
                'weight_per_serving' => 0.5,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 17:53:43',
                'updated_at' => '2025-03-09 17:53:43',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e64062f-cd24-4353-8749-7594785d22be',
                'name' => 'chicken curry sri lankan home made /ලාන්කික කුකුල් මස් කරිය',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'dish[1 chicken piece]',
                'weight_per_serving' => 130,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 18:16:17',
                'updated_at' => '2025-03-09 18:26:24',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e6411d5-c1a8-431e-932f-88d05bb3da11',
                'name' => 'sri lankan style coconut dal curry / ලාන්කීක පොල් කිරි යොදා පිසින ලද පරිප්පු කරිය',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'cup small',
                'weight_per_serving' => 100,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 18:48:51',
                'updated_at' => '2025-03-09 18:48:51',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e641d0e-5832-4cdd-adfd-9ceeab45e803',
                'name' => 'chocolates /චොකොලට්',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'piece',
                'weight_per_serving' => 8,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 19:20:13',
                'updated_at' => '2025-03-09 19:20:13',
                'deleted_at' => null,
            ],
            [
                'food_id' => '9e646f87-8add-4f86-b8ca-ea3881939162',
                'name' => 'Mixed fried rice seafood and chicken  / ම්ශ්‍ර කරන ලද fried rice',
                'description' => null,
                'serving_size' => 1,
                'serving_unit' => 'Cup',
                'weight_per_serving' => 206,
                'image_url' => null,
                'is_active' => true,
                'created_at' => '2025-03-09 23:10:50',
                'updated_at' => '2025-03-09 23:10:50',
                'deleted_at' => null,
            ],
        ];
        
        // Insert the food items
        foreach ($foodItems as $foodItem) {
            FoodItem::updateOrCreate(
                ['food_id' => $foodItem['food_id']],
                $foodItem
            );
        }
        
        $this->command->info('Food items seeded successfully!');
    }
}
